# Guides used:
# https://a-chacon.com/en/docker/2025/01/27/run-deepseek-locally.html
# https://blog.xeynergy.com/running-deepseek-r1-locally-with-ollama-and-docker-9b2b7d05607a

services:
  ollama:
    container_name: ollama-container
    image: ollama/ollama    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1      
    restart: always
    networks:
      - external-net
      - internal-net

  ollama-ubuntu:
    container_name: ollama-ubuntu-container
    build:
      context: .
      dockerfile: dockerfile.models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama:/root/.ollama
    depends_on:
      - ollama
    networks:
      - internal-net
    entrypoint: ["/bin/bash"]
    command: ["-c", "echo 'Starting to pull models...' && ollama pull deepseek-r1:1.5b && ollama pull deepscaler:1.5b && ollama pull deepseek-coder:1.3b && ollama pull deepseek-coder:6.7b && ollama pull moondream && ollama pull llama3.2-vision:11b && ollama pull llama2-uncensored && echo 'All models pulled successfully.'"]

  open-webui:
    container_name: open-webui-container
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - 3000:8080/tcp
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - ollama-ubuntu
    restart: always
    networks:
      - external-net
      - internal-net

networks:
  external-net:
    driver: bridge
  internal-net:
    driver: bridge
    internal: true    

volumes:
  ollama:
  open-webui:
